name: Deploy to Surge

on:
  push:
    branches:
      - master  # O la rama que desees (si es "main" en lugar de "master", cámbialo)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: |
          surge --project ./ --domain nuevo-dominio.surge.sh --token ${{ secrets.SURGE_TOKEN }}
